### ISSUE TITLE
UI testing Nov 4/5, 2021

### ISSUE THREAD

**Issue by johnkit** [johnkit/ace3p-production#4]
On Wed Nov 4:

* Record xml files for 4 tests (excluding setup). Put them in (a new) folder at `test/test-specs/xml`
* Create second projects to play the xml and verify

On Thu Nov 5

* Download overnight build
* Run test and play the xml scripts

**Comment by jaefish** [comment]
assing-color test

[color_error.txt](https://github.com/johnkit/ace3p-production/files/5488949/color_error.txt)

**Comment by jaefish** [comment]
t3p_cavity-quarter test

[t3p_cavity-quarterError.txt](https://github.com/johnkit/ace3p-production/files/5489094/t3p_cavity-quarterError.txt)

**Comment by jaefish** [comment]
Completed t3p_cavity-quarter test:

- Modelbuilder did not recourd the making of monitors

**Comment by jaefish** [comment]
Completed color-assign test:

- Modelbuilder didnt seem to record

**Comment by jaefish** [comment]
I am switching to a dfferent project for now, I assume the issues with recording are human error I will try to debug later today or tomorrow.
